src/Entity/Recettes.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\RecettesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=RecettesRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @ApiResource (
 * collectionOperations={},
 * itemOperations={
 *     "get"={
            "controller"=App\Controller\Api\EmptyController::class,
 *     "read"=false,
 *     "deserialize"=false
 *     }
 * }
 * )
 * @UniqueEntity(
 *  fields={"titre"},
 *  message="titre déjà utilisé merci d'en choisir un autre"
 * )
 */

class Recettes
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Length(min=2, max=40, minMessage="Le titre doit faire plus de 2 caractères", maxMessage="Le titre ne peut pas faire plus de 40 caractères")
     * @ORM\Column(type="string", length=255)
     * @Groups({"read:full:commentaire"})
     */
    private $titre;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @Assert\Length(min=2, max=250, minMessage="La description doit faire plus de 2 caractères", maxMessage="La decription ne peut pas faire plus de 250 caractères")
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @Assert\Length(min=20, minMessage="La recette doit faire plus de 2 caractères")
     * @ORM\Column(type="text")
     */
    private $etapes;

    /**
     * @ORM\ManyToMany(targetEntity=Produits::class, mappedBy="recettesAssociees")
     */
    private $ingredients;

    /**
     * @ORM\OneToMany(targetEntity=Commentaires::class, mappedBy="recette", orphanRemoval=true)
     */
    private $commentaires;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $types;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="recettes")
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Image(mimeTypes={"image/png", "image/jpeg", "image/jpg", "image/gif"}, mimeTypesMessage="Vous devez upload un fichier jpg, png ou gif")
     * @Assert\File(maxSize="1024k", maxSizeMessage="Taille du fichier trop grande")
     */
    private $imgRecette;

    /**
     * Permet d'initialiser le slug automatiquement s'il n'est pas fourni
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function initializeSlug(){
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->titre);
        }
    }

    public function __construct()
    {
        $this->ingredients = new ArrayCollection();
        $this->commentaires = new ArrayCollection();

    }

    /**
     * Permet de récup le notation moyenne de ma recette
     */
    public function getAvgRatings()
    {
        // calculer la somme des notations
        // la fonction php array_reduce permet de réduire le tableau à une seule valeur (attention il faut un tableau et pas une array collection d'où l'utilisation de la méthode toArray()) - 2ème paramètre pour la fonction qui va donner chaque valeur à ajouter et le 3ème paramètre c'est la valeur par défaut
        $sum = array_reduce($this->commentaires->toArray(),function($total,$commentaire){
            return $total + $commentaire->getRating();
        },0);

        // faire la division pour avoir la moyenne (ternaire)
        if(count($this->commentaires) > 0 ) return $moyenne = round($sum / count($this->commentaires));

        return 0;
    }

    /**
     * Permet de récupérer le commentaire d'un auteur par rapport à une recette
     * @param User $author
     * @return Commentaires|null
     */
    public function getCommentFromAuthor(User $author)
    {
        foreach($this->commentaires as $commentaire)
        {
            if($commentaire->getAuthor() === $author) return $commentaire;
        }

        return null;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }
    public function getTypes(): ?string
    {
        return $this->types;
    }

    public function setTypes(string $types): self
    {
        $this->types = $types;

        return $this;
    }
    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getEtapes(): ?string
    {
        return $this->etapes;
    }

    public function setEtapes(string $etapes): self
    {
        $this->etapes = $etapes;

        return $this;
    }

    /**
     * @return Collection|Produits[]
     */
    public function getIngredients(): Collection
    {
        return $this->ingredients;
    }

    public function addIngredient(Produits $ingredient): self
    {
        if (!$this->ingredients->contains($ingredient)) {
            $this->ingredients[] = $ingredient;
            $ingredient->addRecettesAssociee($this);
        }

        return $this;
    }

    public function forEachIngredients($ingredients)
    {
        foreach($ingredients as $ingredient){
            $this->addIngredient($ingredient);
        }
    }

    public function removeIngredient(Produits $ingredient): self
    {
        if ($this->ingredients->removeElement($ingredient)) {
            $ingredient->removeRecettesAssociee($this);
        }

        return $this;
    }

    /**
     * @return Collection|Commentaires[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaires $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setRecette($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaires $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getRecette() === $this) {
                $commentaire->setRecette(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getImgRecette(): ?string
    {
        return $this->imgRecette;
    }

    public function setImgRecette(?string $imgRecette): self
    {
        $this->imgRecette = $imgRecette;

        return $this;
    }

    /**
     * @return Collection|Commentaires[]
     */
    public function getComments(): Collection
    {
        return $this->commentaires;
    }

    public function addComment(Commentaires $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setRecette($this);
        }

        return $this;
    }

    public function removeComment(Commentaires $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getRecette() === $this) {
                $commentaire->setRecette(null);
            }
        }

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use ApiPlatform\Core\Annotation\ApiResource;

use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;



/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *  fields={"email"},
 *  message="email déjà utilisé merci d'en choisir un autre"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"read:commentaire"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email(message="Veuillez renseigner une adresse email valide",groups={"Registration"})
     * @Assert\NotBlank(groups={"Registration"})
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     * @Groups({"read:commentaire"})
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\NotBlank(groups={"Registration"})
     */
    private $password;

    /**
     * @Assert\EqualTo(propertyPath="password", message="Vous n'avez pas correctement confirmé votre mot de passe",groups={"Registration"})
     *
     */
    private $passwordConfirm;

    /**
     * @ORM\OneToMany(targetEntity=Commentaires::class, mappedBy="author", orphanRemoval=true)
     */
    private $commentaires;

    /**
     * @ORM\OneToMany(targetEntity=Recettes::class, mappedBy="author", cascade={"remove"})
     */
    private $recettes;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre prénom")
     * @Groups({"read:commentaire"})
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank (message="Vous devez renseigner votre nom")
     * @Groups({"read:commentaire"})
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Image(mimeTypes={"image/png", "image/jpeg", "image/jpg", "image/gif"}, mimeTypesMessage="Vous devez upload un fichier jpg, png ou gif")
     * @Assert\File(maxSize="1024k", maxSizeMessage="Taille du fichier trop grande")
     */
    private $picture;



    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\Length(min=10, minMessage="Votre presentation doit faire au minimum 10 caractères")
     */
    private $presentation;

    /**
     * Permet d'initialiser le slug automatiquement s'il n'est pas fourni
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function initializeSlug(){
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->firstName.' '.$this->lastName.' '.rand());
        }
    }

    public function getFullName(){
        return "{$this->firstName} {$this->lastName}";
    }


    public function __construct()
    {
        $this->commentaires = new ArrayCollection();
        $this->recettes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     * @return Collection|Commentaires[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }

    public function addCommentaire(Commentaires $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setAuthor($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaires $commentaire): self
    {
        if ($this->commentaires->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getAuthor() === $this) {
                $commentaire->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Recettes[]
     */
    public function getRecettes(): Collection
    {
        return $this->recettes;
    }

    public function addRecette(Recettes $recette): self
    {
        if (!$this->recettes->contains($recette)) {
            $this->recettes[] = $recette;
            $recette->setAuthor($this);
        }

        return $this;
    }

    public function removeRecette(Recettes $recette): self
    {
        if ($this->recettes->removeElement($recette)) {
            // set the owning side to null (unless already changed)
            if ($recette->getAuthor() === $this) {
                $recette->setAuthor(null);
            }
        }

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getPasswordConfirm(): ?string
    {
        return $this->passwordConfirm;
    }

    public function setPasswordConfirm(string $passwordConfirm): self
    {
        $this->passwordConfirm = $passwordConfirm;

        return $this;
    }

    public function getPresentation(): ?string
    {
        return $this->presentation;
    }

    public function setPresentation(?string $presentation): self
    {
        $this->presentation = $presentation;

        return $this;
    }

    /**
     * toString
     * @return string
     */
    public function __toString(){
        return $this->getFullName();
    }



}

templates/recette/_recette.html.twig
{% set url = path('recette_show', {'slug': recette.slug}) %}

<div class="gallery_product">

        <div class="card m-3 cardProduit " style="width: 400px;">
            <a href="{{ url }}">
                <img class="card-img-top " src="/uploads/{{ recette.imgRecette }}" alt="Card image cap" style="height:300px; object-fit: cover;">
            </a>

            <div class="card-body">
                <h2 class="p-2 text-center fw-bolder"> {{ recette.titre }}</h2>

                {% if recette.commentaires | length > 0 %}
                    {% include 'partials/rating.html.twig' with {'rating': recette.avgRatings } %} ({{ recette.comments | length }} avis)
                {% else %}
                    <small>Pas encore noté</small>
                {% endif %}

                <p class="mt-3"><a href="{{ url }}" class="btn btn-default filter-button">En savoir plus</a></p>

            </div>
        </div>

</div>

templates/recette/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification d'une recette{% endblock %}


{% block stylesheets %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    <style>
        input, textarea, select {
            display:block;
            width:100%;
        }
    </style>
{% endblock %}
{% form_theme myForm _self %}
{% block body %}
    {{ form_start(myForm) }}
    <div class="container container2">
        <h1>Modification de la recette</h1>


        <div id="contactForm" class="mt-4"></div>
        <div class="container-fluid">
        <div class="col">{{ form_row(myForm.Titre) }}</div>
        <div class="col descRecette">{{ form_row(myForm.description) }}</div>
        <div class="col steps" id="autoHeight">{{ form_row(myForm.etapes)}}</div>
        <div class="col">{{ form_row(myForm.ingredients) }}</div>
        <div class="col">{{ form_row(myForm.types) }}</div>
        <div class="col">{{ form_row(myForm.imgRecette) }}</div>

        </div>


        {{form_widget(myForm)}}
        <button type="submit" class="btn btn-primary">Ajouter la recette</button>
        {{ form_end(myForm) }}

    </div>
{% endblock %}
{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <script>
        $('.custom-file input').change(function (e) {
            var files = [];
            for (var i = 0; i < $(this)[0].files.length; i++) {
                files.push($(this)[0].files[i].name);
            }
            $(this).next('.custom-file-label').html(files.join(', '));
        });


        $(function(){
            $('.select-tags').select2({
                tags:true,
                tokenSeparators : [',', ' ']
            }).on('change', function (e){
                //je recupere ce qui a été saisi (objet)
                let label = $(this).find("[data-select2-tag=true]");

                //permet de pas rajouter plusieurs fois le meme tag dans la BDD
                //je verifie qu'il y a bien un element && si il existe deja dans la bdd
                if(label.length && $.inArray(label.val(), $(this).val() !== -1)){
                    $.ajax({
                        url:"/recette/new/ajax"+label.val(),
                        type: "POST"

                    }).done(function(data){
                        console.log(data)
                    })
                }
            });

            ;

        })




        $('textarea').on('input', function () {
            this.style.height = "";
            this.style.height = this.scrollHeight + "px";
        });

    </script>

{% endblock %}

templates/recette/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos recettes{% endblock %}

{% block body %}
    <section id="produitGallery">
    <div class="container container2">
        <div class="gallery col-lg-12 col-md-12 col-sm-12 col-xs-12 mx-auto">
        <h1 class="display-2 text-center mb-4 mt-4">Recette</h1>
        <div class="recetteIndexMobile">
            {% for recette in recettes %}
             {% include 'recette/_recette.html.twig' %}
            {% endfor %}
        </div>
    </div>
    </section>
{% endblock %}

templates/recette/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout d'une recette{% endblock %}

{% block stylesheets %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>

    <style>
        input, textarea, select {
            display: block;
            width: 100%;
        }
    </style>
{% endblock %}

{% form_theme myForm _self %}

{% block body %}
    {{ form_start(myForm) }}
    <div class="container container2">
        <h1 class="display-2 text-center">Création d'une nouvelle recette</h1>

        <div id="contactForm" class="mt-4"></div>
        <div class="container-fluid">
            <div class="col">{{ form_row(myForm.Titre) }}</div>
            <div class="col descRecette">{{ form_row(myForm.description) }}</div>
            <div class="col steps" id="autoHeight">{{ form_row(myForm.etapes) }}</div>
            <div class="col">{{ form_row(myForm.ingredients) }}</div>
            <div class="col">{{ form_row(myForm.types) }}</div>
            <div class="col">{{ form_row(myForm.imgRecette) }}</div>
            <div class="col">
                <button type="submit" class="btn btn-primary">Ajouter la recette</button>
            </div>
        </div>


        {{ form_widget(myForm) }}
        {{ form_end(myForm) }}

    </div>
{% endblock %}
{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="jquery-3.5.1.min.js"></script>
    <script>
        // permet d'afficher le nom du fichier a upload
        $('.custom-file input').change(function (e) {
            var files = [];
            for (var i = 0; i < $(this)[0].files.length; i++) {
                files.push($(this)[0].files[i].name);
            }
            $(this).next('.custom-file-label').html(files.join(', '));
        });

        // fonction recherche pour l'ajout des ingredients
        $(function () {
            $('.select-tags').select2({
                tags: true,
                tokenSeparators: [',', ' ']
            }).on('change', function (e) {
                //je recupere ce qui a été saisi (objet)
                let label = $(this).find("[data-select2-tag=true]");

                //permet de pas rajouter plusieurs fois le meme tag dans la BDD
                //je verifie qu'il y a bien un element && si il existe deja dans la bdd
                if (label.length && $.inArray(label.val(), $(this).val() !== -1)) {
                    $.ajax({
                        url: "/recette/new/ajax" + label.val(),
                        type: "POST"

                    }).done(function (data) {
                        console.log(data)
                    })
                }
            });

            ;

        })
    </script>
{% endblock %}

templates/recette/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recette: {{ recette.titre }}{% endblock %}

{% block body %}

    <div class="container container2">


        <h1 class="display-2 text-center mb-4">{{ recette.titre }}</h1>

        <img src="/uploads/{{ recette.imgRecette }}" class="img-fluid mb-5"
             style="width:100%; object-fit: contain; max-height:300px;">


        {% if (app.user and app.user == recette.author) or is_granted('ROLE_ADMIN') %}
            <div class="text-center mb-3">
                <a href="{{ path('recette_edit',{'slug': recette.slug}) }}" class="btn btn-secondary">Modification de la
                    recette</a>

                <a href="{{ path('recette_delete',{'slug': recette.slug}) }}" class="btn btn-danger"
                   onclick="return confirm('êtes vous sûr de vouloir supprimer la recette: {{ recette.titre }}')">Supprimer</a>
            </div>
        {% endif %}


        <p class="recetteTxt text-justify text-center mb-5">{{ recette.description }}</p>
        <p class="recetteSteps">{{ recette.etapes  | raw | nl2br }}</p>




        {% for recette in recette.getIngredients() %}
            {% set url = path('produit_show', {'slug': recette.getSlug()}) %}
            <a href="{{ url }}" class="btn btn-secondary">{{ recette.getNom() }}</a>
            <br>
        {% endfor %}



        <div class="col d-flex flex-column justify-content-center text-center">
                         {% set a = recette.author %}

                                 <a href="{{ path('user_show', {'slug' : a.slug })}}">
                                     {% if a.picture %}
                                         <img src="/uploads/{{a.picture}}" class="avatar avatar-medium" alt="Avatar de {{a.fullName}}">
                                     {% else %}
                                         <img src="http://placehold.it/300x300" class="avatar avatar-medium" alt="Avatar de {{a.fullName}}">
                                     {% endif %}
                                 </a>

                             <div class="col">
                                 <a href="{{ path('user_show', {'slug' : a.slug })}}">
                                     <h3>{{a.fullName}}</h3>
                                 </a>
                                 <span class="badge badge-primary">{{a.recettes | length }} annonces</span>
                             </div>

                         {{ a.presentation | raw | nl2br }}
                     </div>



    </div>

    <div class="col">

        {# exemple : ad.author.fullName devient a.fullName #}
        {# gestion des commentaires
        {% set a = recette.author %}
        <hr>
        {% if app.user %}
            <div class="alert alert-light" id="comment">
                {% set comment = recette.commentFromAuthor(app.user) %}
                {% if comment is not null %}

                    <blockquote>
                        {{ comment.contenu }}
                    </blockquote>
                    <strong>Note: </strong>{% include 'partials/rating.html.twig' with {'rating': comment.rating} %}
                {% else %}
                    {{ form_start(myForm) }}
                    {{ form_widget(myForm) }}
                    <button type="submit" class="btn btn-success">Confirmer</button>
                    {{ form_end(myForm) }}
                {% endif %}
            </div>
        {% endif %}

        {% if recette.commentaires | length > 0 %}
            <h2 class="mb-3">Commentaires de nos utilisateurs: </h2>

            <div class="alert alert-info">
                <h4 class="alert-heading text-center">
                    <div class="row align-items-center">
                        <div class="col">
                            Note globale
                        </div>
                        <div class="col">
                            {% include 'partials/rating.html.twig' with {'rating': recette.avgRatings } %}
                            <br><small>(Cette moyenne est calculée sur {{ recette.commentaires | length }} avis)</small>
                        </div>
                    </div>
                </h4>
            </div>

            {% for commentaire in recette.commentaires %}
                <div class="bg-light rounded mb-3 py-3 px-3">
                    <strong>{{ commentaire.author.firstName }}</strong> a dit:
                    <blockquote>
                        {{ commentaire.contenu | nl2br }}
                    </blockquote>
                    <strong>Note donnée: </strong>
                    {% include 'partials/rating.html.twig' with {'rating': commentaire.rating} %}
                </div>
            {% endfor %}
        {% else %}
            <h2>Cette annonce n'a pas encore reçu de commentaire ...</h2>
        {% endif %}
        #}

        <post-comments data-post="{{ recette.id }}" data-user="{{ app.user ? app.user.id  : 0 }}" data-role="{{ app.user ? app.user.roles|json_encode }}"></post-comments>


    </div>

{% endblock %}